export const pizzaData = [
	{
		id: 1,
		title: 'Fresh Veggie',
		img: 'Pizzas/Fresh_Veggie.jpg',
		price: 11,
		info: 'Onion and capsicum',
		inCart: false,
		count: 0,
		total: 0,
	},
	{
		id: 2,
		title: 'Farm House',
		img: 'Pizzas/Farmhouse.jpg',
		price: 12.75,
		info: 'Capsicum, mushroom and tomatoes',
		inCart: false,
		count: 0,
		total: 0,
	},
	{
		id: 3,
		title: 'Cheese N Corn',
		img: 'Pizzas/Corn_&_Cheese.jpg',
		price: 10,
		info: 'Cheese and golden corn',
		inCart: false,
		count: 0,
		total: 0,
	},
	{
		id: 4,
		title: 'Double Cheese Margherita',
		img: 'Pizzas/Double_Cheese_Margherita.jpg',
		price: 8.5,
		info: 'Margherita loaded with extra cheese',
		inCart: false,
		count: 0,
		total: 0,
	},
	{
		id: 5,
		title: 'Indian Tandoori Paneer',
		img: 'Pizzas/IndianTandooriPaneer.jpg',
		price: 14.6,
		info: 'Tandoori paneer with capsicum, red paprika and mint mayo',
		inCart: false,
		count: 0,
		total: 0,
	},
	{
		id: 6,
		title: 'Mexican Green Wave',
		img: 'Pizzas/Mexican_Green_Wave.jpg',
		price: 16,
		info: 'Onion, capsicum, tomatoes and jalapeno with mexican herbs',
		inCart: false,
		count: 0,
		total: 0,
	},
	{
		id: 7,
		title: 'Peppy Paneer',
		img: 'Pizzas/Peppy_Paneer.jpg',
		price: 14,
		info: 'Paneer with crisp capsicum and spicy red paneer',
		inCart: false,
		count: 0,
		total: 0,
	},
	{
		id: 8,
		title: 'Paneer Makhani',
		img: 'Pizzas/Paneer_Makhni.jpg',
		price: 15,
		info: 'Paneer and capsicum on makhani sauce',
		inCart: false,
		count: 0,
		total: 0,
	},
];
